sim.excel.file=VDC_23_V1.0_A.xlsx
excel.sheet=VDC_23;VAB_VDC_23

# DRIVER → IP:PORT
MODBUS_LGRNG=192.168.20.25:502
MODBUS_GE=192.168.20.61:502
MODBUS_SHM=192.168.20.37:502
MODBUS_PANDORA=192.168.20.67:502
ADS_BIL=192.168.20.68:502

# COLONNE ADDRESS
MODBUS_ADDRESS_SHM=41
MODBUS_ADDRESS_GE=41
MODBUS_ADDRESS_LGRNG=41
MODBUS_ADDRESS_PANDORA=43
ADS_ADDRESS_BIL=45

MODBUS_CYCLE_TIME_SHM=500
MODBUS_CYCLE_TIME_GE=1000
MODBUS_CYCLE_TIME_LGRNG=2000
MODBUS_CYCLE_TIME_PANDORA=500
ADS_CYCLE_TIME_BIL=500

