sim.excel.file=VDC_21_V1.3_A_VB4_GIO.xlsx
excel.sheet=VDC_21

# DRIVER → IP:PORT
MODBUS_LGRNG=192.168.20.25:502
MODBUS_GE=192.168.20.61:502
MODBUS_SHM=192.168.20.37:502
MODBUS_PANDORA=192.168.20.67:502

# COLONNE ADDRESS
MODBUS_ADDRESS_SHM=40
MODBUS_ADDRESS_GE=40
MODBUS_ADDRESS_LGRNG=40
MODBUS_ADDRESS_PANDORA=42

MODBUS_CYCLE_TIME_SHM=500
MODBUS_CYCLE_TIME_GE=1000
MODBUS_CYCLE_TIME_LGRNG=2000
MODBUS_CYCLE_TIME_PANDORA=500

